---
output:
  knitrBootstrap::bootstrap_document:
    theme.chooser: TRUE
    highlight.chooser: TRUE
---

Visualize Neun+ peaks
=====================


# Setup

```{r 'setup', dev = 'CairoPNG', bootstrap.show.code = FALSE}
library('knitr')
opts_chunk$set(dev = 'CairoPNG')
```


```{r}
library('GenomicRanges')
library('derfinder')
library('derfinderPlot')
library('bumphunter')
library('TxDb.Hsapiens.UCSC.hg19.knownGene')
library('devtools')

## Load data
load('/dcl01/lieber/ajaffe/derRuns/derfinderExample/derGenomicState/GenomicState.Hsapiens.UCSC.hg19.knownGene.Rdata')
load('neunPeaks.Rdata')
load(file.path('..', 'CoverageInfo', 'fullCov.Rdata'))
load(file.path('..', 'derAnalysis', 'run6-v1.5.34', 'groupInfo.Rdata'))
load(file.path('..', 'derAnalysis', 'run6-v1.5.34', 'colsubset.Rdata'))

## Keep only samples used
fullCov <- lapply(fullCov, function(x) { x[, colsubset]})

## Add padding to peaks
neunPeaks.pad <- resize(neunPeaks, round(width(neunPeaks) * 1.1, 0), fix = 'center')
## A small fraction overlaps
table(countOverlaps(neunPeaks.pad) - 1)
```

# Plots

Region coverage plots for Neun+ peaks separated by direction: top 100 regions ordered by log ratio for each direction. Plots have 10% padding (5% on each end).

## Up

```{r}
idx <- neunPeaks.pad$Direction == 'Up'

## Get region coverage
regionCov <- getRegionCoverage(fullCov, neunPeaks.pad[idx])

## Genes
genes <- annotateTranscripts(txdb = TxDb.Hsapiens.UCSC.hg19.knownGene::TxDb.Hsapiens.UCSC.hg19.knownGene)

## Nearest annotation
annoNear <- matchGenes(neunPeaks.pad[idx], subject = genes)

## Genomic states
annoReg <- annotateRegions(neunPeaks.pad[idx], GenomicState.Hsapiens.UCSC.hg19.knownGene$fullGenome)

## Plots
pdf('neunPeaks_up_top100.pdf')
plotRegionCoverage(neunPeaks.pad[idx], regionCov, groupInfo, annoNear, annoReg, TxDb.Hsapiens.UCSC.hg19.knownGene, head(order(abs(neunPeaks.pad$LogRatio[idx]), decreasing = TRUE), n = 100))
dev.off()
```


## Down

```{r}
## Get region coverage
regionCov <- getRegionCoverage(fullCov, neunPeaks.pad[!idx])

## Nearest annotation
annoNear <- matchGenes(neunPeaks.pad[!idx], genes)

## Genomic states
annoReg <- annotateRegions(neunPeaks.pad[!idx], GenomicState.Hsapiens.UCSC.hg19.knownGene$fullGenome)

## Plots
pdf('neunPeaks_down_top100.pdf')
plotRegionCoverage(neunPeaks.pad[!idx], regionCov, groupInfo, annoNear, annoReg, TxDb.Hsapiens.UCSC.hg19.knownGene, head(order(abs(neunPeaks.pad$LogRatio[!idx]), decreasing = TRUE), n = 100))
dev.off()
```

# Reproducibility

```{r}
## Reproducibility info
options(width = 120)
session_info()
Sys.time()
```
